### PR TITLE
Extend animator functionality to stop and resume car animation.

### PR DESCRIPTION
**Pull request by NicolasCombe5555**
Also:
Added CLLocationCoordinate2D extensions.
Added buttons to mapView programmatically.
Added pause and play icons.

---Happy Hacktoberfest

### CODE REVIEW

**Comment by SURYAKANTSHARMA** [comment]
@NicolasCombe5555  Thanks a lot for PR. Could you please update Read me gif file with updated

**Comment by NicolasCombe5555** [comment]
Yes, will do.

**Comment by NicolasCombe5555** [comment]
@SURYAKANTSHARMA I updated the read me. Let me know if it looks good

**Review by SURYAKANTSHARMA — APPROVED** [review]

**Comment by SURYAKANTSHARMA** [comment]
Thanks @NicolasCombe5555 💯

**Comment by NicolasCombe5555** [comment]
I actually found you repo some months ago when i was trying to animate markers in google maps, and i got back to you with hacktoberfest. I will try and see how else can i contribute to your project. Its really helpful. Cheers!

**Pull request merged**
